reverted changes

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -14,9 +14,9 @@ fi
 if [ -e ${module}.ko ]; then
     echo "Loading local built file ${module}.ko"
     modprobe ${module} || exit 1
-# else
-#     echo "Local file ${module}.ko not found, attempting to modprobe"
-#     modprobe ${module} || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
 fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
